//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PO_OPBalance
    {
        public int AUTOCODE { get; set; }
        public string PLANT { get; set; }
        public string ORDER_TYPE { get; set; }
        public string PO_DOC_NO { get; set; }
        public int ITEM_NO_OF_PODOC { get; set; }
        public decimal PO_QTY { get; set; }
        public decimal Dispatch_QTY { get; set; }
        public decimal Balance_QTY { get; set; }
        public Nullable<int> VENDOR_CODE { get; set; }
        public decimal Dispatch_ASOn { get; set; }
    }
}
