//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PO_SchDailyDetail
    {
        public int DailyId { get; set; }
        public string PONo { get; set; }
        public Nullable<int> POLineItemNo { get; set; }
        public Nullable<System.DateTime> SchDate { get; set; }
        public Nullable<decimal> SchQty { get; set; }
        public string Entry_type { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
