//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SMSLOG
    {
        public int SmsLogId { get; set; }
        public string VendorLoginId { get; set; }
        public string SmsTo { get; set; }
        public Nullable<System.DateTime> SmsDateTime { get; set; }
        public string SmsFrom { get; set; }
        public Nullable<int> SmsSentById { get; set; }
        public string Remark { get; set; }
    }
}
