//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_PLANT
    {
        public string PLANT { get; set; }
        public string PLANT_NAME { get; set; }
        public string GSTNumber { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
        public Nullable<bool> ScheduleYN { get; set; }
    }
}
