//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_System_Parameter
    {
        public int P_SystemPara { get; set; }
        public string CompCode { get; set; }
        public Nullable<int> Comp_RetirementAge { get; set; }
        public Nullable<int> MinJoinAge { get; set; }
        public Nullable<bool> MaintenanceMode { get; set; }
        public string MaintenanceHour { get; set; }
        public string compRegionCode { get; set; }
        public string DisplayCommanMessage { get; set; }
    }
}
