//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_UserFormMapping
    {
        public int User_Form_MapId { get; set; }
        public Nullable<int> F_UserId { get; set; }
        public Nullable<int> F_FormId { get; set; }
        public Nullable<bool> F_Add { get; set; }
        public Nullable<bool> F_Update { get; set; }
        public Nullable<bool> F_Delete { get; set; }
        public Nullable<bool> F_Print { get; set; }
        public Nullable<bool> F_Export { get; set; }
    
        public virtual M_Forms M_Forms { get; set; }
        public virtual User User { get; set; }
    }
}
