//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_VENDOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_VENDOR()
        {
            this.M_MACID = new HashSet<M_MACID>();
        }
    
        public int Vendor_Code { get; set; }
        public string Vendor_Name { get; set; }
        public string Vendor_Name2 { get; set; }
        public string Vendor_Name3 { get; set; }
        public bool Vendor_Lock_YN { get; set; }
        public string SearchTerm { get; set; }
        public string Street2 { get; set; }
        public string Street3 { get; set; }
        public string Street { get; set; }
        public string HouseNo { get; set; }
        public string Street4 { get; set; }
        public string Street5 { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Region { get; set; }
        public string Tital { get; set; }
        public string Country { get; set; }
        public string Telephone1 { get; set; }
        public string Telephone2 { get; set; }
        public string Fax_No { get; set; }
        public string Email_Id { get; set; }
        public bool MultiItem_Invoice_YN { get; set; }
        public string Vendor_LogInId { get; set; }
        public string Vendor_LogInPassword { get; set; }
        public Nullable<bool> Vendor_Registered_YN { get; set; }
        public string Registered_Mobile_For_OTP { get; set; }
        public string CentralPostingBlock { get; set; }
        public string CentralPurchasingBlock { get; set; }
        public string BlockFunction { get; set; }
        public string Vendor_Address { get; set; }
        public Nullable<System.DateTime> Vendor_Last_Login { get; set; }
        public string OTP { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedIP { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedIP { get; set; }
        public Nullable<int> Vendor_LockBy { get; set; }
        public Nullable<System.DateTime> Vendor_LockOn { get; set; }
        public Nullable<int> Vendor_UnLockBy { get; set; }
        public Nullable<System.DateTime> Vendor_UnLockOn { get; set; }
        public string LoginType { get; set; }
        public Nullable<int> ChangePasswordBy { get; set; }
        public Nullable<System.DateTime> ChangePasswordOn { get; set; }
        public string TaxNumber3_GST { get; set; }
        public string GST_Ven_Class { get; set; }
        public string RegionName { get; set; }
        public string RegionCode { get; set; }
        public string DisplayMessage { get; set; }
        public Nullable<bool> UploadInvoice { get; set; }
        public Nullable<bool> ScheduleYN { get; set; }
        public string ScheduleType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_MACID> M_MACID { get; set; }
    }
}
