//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PODB20171004121158_04OCT2017_6001
    {
        public string Plant { get; set; }
        public string Order_Type { get; set; }
        public string Purchasing_Document { get; set; }
        public string Purchase_Order_Date { get; set; }
        public string Item_Number { get; set; }
        public string PO_Quantity { get; set; }
        public string Balance_Quantity { get; set; }
        public decimal Dispatch_QTY { get; set; }
        public decimal PO_QTY { get; set; }
        public decimal Balance_QTY { get; set; }
        public Nullable<int> VENDOR_CODE { get; set; }
    }
}
