//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_AIN_DOCNO
    {
        public int AUTOCODE { get; set; }
        public string AIN_NO { get; set; }
        public Nullable<int> FINV_ID { get; set; }
        public string PLANT { get; set; }
        public Nullable<int> VENDOR_CODE { get; set; }
        public Nullable<int> DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_ON { get; set; }
        public bool DELETED_FLAG { get; set; }
    }
}
