//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PO_SchMonthlyWeeklyDetail
    {
        public int MonthlyWeeklyId { get; set; }
        public string PONo { get; set; }
        public Nullable<int> POLineItemNo { get; set; }
        public Nullable<decimal> MonthlySchQty { get; set; }
        public Nullable<System.DateTime> MonthlySchDate { get; set; }
        public Nullable<decimal> W1SchQty { get; set; }
        public Nullable<decimal> W2SchQty { get; set; }
        public Nullable<decimal> W3SchQty { get; set; }
        public Nullable<decimal> W4SchQty { get; set; }
        public string Entry_type { get; set; }
        public Nullable<int> CreatedBy1 { get; set; }
        public Nullable<System.DateTime> CreatedOn1 { get; set; }
        public Nullable<int> CreatedBy2 { get; set; }
        public Nullable<System.DateTime> CreatedOn2 { get; set; }
        public Nullable<int> CreatedBy3 { get; set; }
        public Nullable<System.DateTime> CreatedOn3 { get; set; }
        public Nullable<int> CreatedBy4 { get; set; }
        public Nullable<System.DateTime> CreatedOn4 { get; set; }
        public Nullable<int> ModifiedBy1 { get; set; }
        public Nullable<System.DateTime> ModifiedOn1 { get; set; }
        public Nullable<int> ModifiedBy2 { get; set; }
        public Nullable<System.DateTime> ModifiedOn2 { get; set; }
        public Nullable<int> ModifiedBy3 { get; set; }
        public Nullable<System.DateTime> ModifiedOn3 { get; set; }
        public Nullable<int> ModifiedBy4 { get; set; }
        public Nullable<System.DateTime> ModifiedOn4 { get; set; }
    }
}
